hibernate.connection.driver_class=org.postgresql.Driver
hibernate.connection.url=jdbc:postgresql://localhost:5432/binar_course
hibernate.connection.username=bagas
hibernate.connection.password=binar2026

hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
hibernate.default_schema=finance

hibernate.show_sql=true
hibernate.format_sql=true
hibernate.highlight_sql=true